tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-versions"
tap "homebrew/cask-fonts"
tap "homebrew/core"
brew "awscli"
brew "bash"
brew "bash-completion"
brew "python"
brew "git"
brew "gnu-sed"
brew "go"
brew "hub"
brew "jq"
brew "node"
brew "shellcheck"
brew "tfenv"
brew "the_silver_searcher"
brew "watch"
brew "wget"
brew "yarn"
brew "yarn-completion"
cask "visual-studio-code"
cask "vlc"
cask "zoomus"
# MS Office - only if client work requires it
## cask "microsoft-excel"
## cask "microsoft-powerpoint"
cask "microsoft-word"
# Mostly for local cross-browser testing
## cask "virtualbox"
## cask "virtualbox-extension-pack"
cask "google-chrome-canary"
## cask "firefox"
cask "font-jetbrains-mono"
mas "meeter", id: 1510445899
