tap "beeftornado/rmtree"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
brew "awscli"
brew "bash"
brew "python"
brew "credstash"
brew "gnu-sed"
brew "go"
brew "httpstat"
brew "hub"
brew "jq"
# node@12 formula depends only on icu4c but it comes with small-icu built-in anyway
brew "node@12", args: ["ignore-dependencies"] 
brew "openvpn"
brew "shellcheck"
brew "tfenv"
brew "the_silver_searcher"
brew "unrar"
brew "watch"
brew "wget"
# yarn formula depends only on node (latest) but I want node@12
brew "yarn", args: ["ignore-dependencies"]
brew "youtube-dl"
cask "authy"
cask "brave-browser"
cask "docker"
cask "firefox"
cask "google-chrome"
cask "google-chrome-canary"
cask "kindle"
cask "microsoft-excel"
cask "microsoft-powerpoint"
cask "microsoft-word"
cask "slack"
cask "spotify"
cask "telegram"
cask "virtualbox"
cask "virtualbox-extension-pack"
cask "visual-studio-code"
cask "vlc"
cask "zoomus"